#!/usr/bin/env bash
#displays Best School 10 times,
#but for the 9th iteration, displays Best School and then Hi on a new line.

n=1
while [ $n -le 10 ]
do
   if [ $n -eq 9 ]
   then
       echo "Best School"
       echo "Hi"
   fi
   if [ $n -ne 9 ]
   then
       echo "Best School"
   fi
   (( ++n ))
done
